create table public.appointments (
  id bigint generated by default as identity primary key,
  date date not null,
  time time not null,
  label text default ''
);

create table public.responses (
  id bigint generated by default as identity primary key,
  name text not null,
  no_need boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.response_slots (
  response_id bigint not null references public.responses(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  primary key(response_id,appointment_id)
);

alter table public.appointments enable row level security;
alter table public.responses enable row level security;
alter table public.response_slots enable row level security;

-- The Node.js server uses the Supabase service-role key.
-- Do not expose that key in browser code.
-- RLS therefore prevents accidental public database access.
